### PR TITLE
Add standardjs, restructure tests and update to ES2015

### PR DESCRIPTION
**Pull request by corbinu**
I understand this is a very large change. If you want any different linting or to not merge it at all I totally understand.

Am planning to make a lot more contributions in the future just wanted to modernize things a bit first.

### CODE REVIEW

**Comment by bojand** [comment]
Hello, thanks for the PR! I agree this package could use some love in cleaning up code and modernizing it like this. In fact I started doing something similar in a [branch](https://github.com/bojand/mailgun-js/tree/code_improvements) a while ago but never got to finish it. One thing I would request is to use [StandardJS](https://standardjs.com/) for code style and linting for all the reasons [they list](https://standardjs.com/#why-should-i-use-javascript-standard-style). You can still set env's similarly to how you have already:

```json
"standard": {
    "env": {
      "node": true,
      "mocha": true
    }
  }
```

Maybe address that and I'll look over everything and we'll try and get this merged.

Thanks

**Comment by corbinu** [comment]
Sure is your project will switch

**Comment by corbinu** [comment]
@bojand Done

**Comment by bojand** [comment]
Thanks for this! Published as 0.14.0.

**Pull request merged**
